# Lazygit Configuration
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  # Theme
  theme:
    activeBorderColor:
      - '#7aa2f7'
      - bold
    inactiveBorderColor:
      - '#3b4261'
    searchingActiveBorderColor:
      - '#7aa2f7'
      - bold
    optionsTextColor:
      - '#a9b1d6'
    selectedLineBgColor:
      - '#3b4261'
    selectedRangeBgColor:
      - '#3b4261'
    cherryPickedCommitBgColor:
      - '#7aa2f7'
    cherryPickedCommitFgColor:
      - '#1a1b26'
    unstagedChangesColor:
      - '#db4b4b'
    defaultFgColor:
      - '#c0caf5'
  # Layout
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  # UI behavior
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: 'margin'
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: 'flexible'
  # Time format
  timeFormat: '02 Jan 06'
  shortTimeFormat: '3:04PM'
  # Icons (requires Nerd Font)
  showIcons: true
  nerdFontsVersion: '3'
  # Border
  border: 'rounded'
  # Commits
  showGraph: 'always'
  skipHookPrefix: 'WIP'
  autoFetch: true
  autoRefresh: true
  branchLogCmd: 'git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
  allBranchesLogCmd: 'git log --graph --all --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
  # Commit length
  commitLength:
    show: true
  # Language
  language: 'auto'
git:
  # Paging
  paging:
    colorArg: always
    pager: delta
  # Commit
  commit:
    signOff: false
    verbose: default
  # Merging
  merging:
    manualCommit: false
    args: ''
  # Log
  log:
    order: 'topo-order'
    showGraph: 'always'
    showWholeGraph: false
  # Pull
  pull:
    mode: 'rebase'
  # Push
  push:
    auto: true
  # Fetching
  fetchAll: true
  # Branch
  branchLogCmd: 'git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'
  # Diff
  skipHookPrefix: 'WIP'
  autoFetch: true
  autoRefresh: true
  # Main branches
  mainBranches:
    - master
    - main
    - develop
  # Parse emoji
  parseEmoji: true
os:
  # Editor
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} {{filename}}'
  editAtLineAndWait: 'nvim +{{line}} {{filename}}'
  editInTerminal: true
  # Opening files
  open: 'xdg-open {{filename}} >/dev/null'
  openLink: 'xdg-open {{link}} >/dev/null'
# Keybindings
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    toggleRangeSelect: 'v'
    rangeSelectDown: '<s-down>'
    rangeSelectUp: '<s-up>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextBlock-alt2: '<tab>'
    prevBlock-alt2: '<backtab>'
    jumpToBlock: ['1', '2', '3', '4', '5']
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    optionMenu: 'x'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmInEditor: '<a-enter>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeShellCommand: ':'
    createRebaseOptionsMenu: 'm'
    # Push/pull/fetch
    pushFiles: 'P'
    pullFiles: 'p'
    # Refresh
    refresh: 'R'
    # Copy
    copyToClipboard: '<c-o>'
  # Status panel
  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
    allBranchesLogGraph: 'a'
  # Files panel
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: '<c-f>'
    confirmDiscard: 'x'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    openMergeTool: 'M'
    openStatusFilter: '<c-b>'
  # Branches panel
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    copyPullRequestURL: '<c-y>'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    renameBranch: 'R'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    createTag: 'T'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'
  # Worktrees
  worktrees:
    viewWorktreeOptions: 'w'
  # Commits
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    resetCommitAuthor: 'a'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'c'
    pasteCommits: 'v'
    markCommitAsBaseForRebase: 'B'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitAttributeToClipboard: 'y'
    openLogMenu: '<c-l>'
    openInBrowser: 'o'
    viewBisectOptions: 'b'
    startInteractiveRebase: 'i'
  # Stash
  stash:
    popStash: 'g'
    renameStash: 'r'
  # Commit message
  commitMessage:
    commitMenu: '<c-o>'
  # Main panel (normal mode)
  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
    editSelectHunk: 'e'
  # Submodules
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'
# Custom commands
customCommands:
  - key: '<c-r>'
    context: 'files'
    description: 'Reload'
    command: 'git status'
# Refresher
refresher:
  refreshInterval: 10
  fetchInterval: 60
# Update
update:
  method: prompt
  days: 14
# Confirmation on quit
quitOnTopLevelReturn: false
confirmOnQuit: false
# Disable animations
disableStartupPopup: true
notARepository: 'prompt'
